import java.sql.Connection;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Gaming-PC010
 */
public class Login extends javax.swing.JFrame {

    
    Connection con = null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    
    
    Color panDefualt,panEnter,panClick;
    public Login() {
        initComponents();
        
        panDefualt=new Color(255,153,0);
        panClick=new Color(243,183,68);
        panEnter=new Color(243,98,43);
         
        jPanLogin.setBackground(panDefualt);
        
        
        con=ConnectionString.DbConnection();
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTUsername = new javax.swing.JTextField();
        jPPassword = new javax.swing.JPasswordField();
        jPanLogin = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 153, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 50)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Login");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 146, -1));
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 110, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("BARANGAY LAPASAN");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-user-groups-100.png"))); // NOI18N
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 510));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Username");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 120, 40));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 300, 260, -1));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 260, -1));

        jTUsername.setBackground(new java.awt.Color(0, 51, 51));
        jTUsername.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTUsername.setForeground(new java.awt.Color(255, 255, 255));
        jTUsername.setBorder(null);
        jTUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTUsernameActionPerformed(evt);
            }
        });
        jPanel1.add(jTUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 152, 260, 30));

        jPPassword.setBackground(new java.awt.Color(0, 51, 51));
        jPPassword.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPPassword.setForeground(new java.awt.Color(255, 255, 255));
        jPPassword.setBorder(null);
        jPPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPPasswordKeyPressed(evt);
            }
        });
        jPanel1.add(jPPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, 260, 40));

        jPanLogin.setBackground(new java.awt.Color(255, 153, 0));
        jPanLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanLoginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanLoginMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanLoginMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanLoginMouseReleased(evt);
            }
        });
        jPanLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanLoginKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Login");

        javax.swing.GroupLayout jPanLoginLayout = new javax.swing.GroupLayout(jPanLogin);
        jPanLogin.setLayout(jPanLoginLayout);
        jPanLoginLayout.setHorizontalGroup(
            jPanLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanLoginLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanLoginLayout.setVerticalGroup(
            jPanLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel1.add(jPanLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, 190, 60));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Password");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, 120, 40));

        jLabel10.setIcon(new javax.swing.ImageIcon("d:\\Downloads\\Semi\\JAVA\\icons8-close-window-50.png")); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 509));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTUsernameActionPerformed
      
    }//GEN-LAST:event_jTUsernameActionPerformed

    private void jPanLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanLoginMouseEntered
          jPanLogin.setBackground(panEnter);  
        
        
    }//GEN-LAST:event_jPanLoginMouseEntered

    private void jPanLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanLoginMouseExited
              jPanLogin.setBackground(panDefualt);
        
    }//GEN-LAST:event_jPanLoginMouseExited

    private void jPanLoginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanLoginMousePressed
        // TODO add your handling code here:
        jPanLogin.setBackground(panClick);
    }//GEN-LAST:event_jPanLoginMousePressed

    private void jPanLoginMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanLoginMouseReleased
  // TODO add your handling code here:
  
        jPanLogin.setBackground(panDefualt);
    }//GEN-LAST:event_jPanLoginMouseReleased

    private void jPanLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanLoginMouseClicked
        try{
            String url="Select * from UserDetails where Username=? AND Password=?";
            pst=con.prepareStatement(url);
            pst.setString(1,jTUsername.getText());
            pst.setString(2,jPPassword.getText());
            rs=pst.executeQuery();
            
            
            //check username and Password
            
            if(rs.next()){
            
                JOptionPane.showMessageDialog(null,"Login Successful");
                NDashboard d = new NDashboard();
                d.setVisible(true);
                this.dispose();
            }
            else
                JOptionPane.showMessageDialog(null,"Username or Password is incorect");
                   
        }
        catch(Exception e){
           NDashboard d = new NDashboard();
                d.setVisible(true);
                this.dispose();
        
        
        }
        
    }//GEN-LAST:event_jPanLoginMouseClicked

    private void jPanLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanLoginKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            
            try{
            String url="Select * from UserDetails where Username=? AND Password=?";
            pst=con.prepareStatement(url);
            pst.setString(1,jTUsername.getText());
            pst.setString(2,jPPassword.getText());
            rs=pst.executeQuery();
            
            
            //check username and Password
            
            if(rs.next()){
            
                JOptionPane.showMessageDialog(null,"Login Successful");
                NDashboard d = new NDashboard();
                d.setVisible(true);
                this.dispose();
            }
            else
                JOptionPane.showMessageDialog(null,"Username or Password is incorect");
                   
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Checking Failed"+ e);
        
        
        }
      
        
        
        }
       
        
       
        
    }//GEN-LAST:event_jPanLoginKeyPressed

    private void jPPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPPasswordKeyPressed
        
         if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            
            try{
            String url="Select * from UserDetails where Username=? AND Password=?";
            pst=con.prepareStatement(url);
            pst.setString(1,jTUsername.getText());
            pst.setString(2,jPPassword.getText());
            rs=pst.executeQuery();
            
            
            //check username and Password
            
            if(rs.next()){
            
                JOptionPane.showMessageDialog(null,"Login Successful");
                NDashboard d = new NDashboard();
                d.setVisible(true);
                this.dispose();
            }
            else
                JOptionPane.showMessageDialog(null,"Username or Password is incorect");
                   
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Checking Failed"+ e);
        
        
        }
        
        
        
        
        
        
        
         }   
        
        
        
    }//GEN-LAST:event_jPPasswordKeyPressed

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel10MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPPassword;
    private javax.swing.JPanel jPanLogin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTUsername;
    // End of variables declaration//GEN-END:variables
}
